import type { AppState } from "./types";

export const seedState: AppState = {
  user: {
    id: "user-owner",
    name: "Propietario",
    email: "owner@example.local",
    avatar: "PO",
    locale: "es-DO",
    timezone: "America/Santo_Domingo",
    status: "signed_in",
    provider: "local",
    currentMemberId: "m1",
    createdAt: "2026-05-01",
    lastLoginAt: "2026-05-31",
  },
  activeSpaceId: "space-home",
  spaces: [
    {
      id: "space-home",
      name: "Mi Hogar",
      kind: "family",
      currency: "DOP",
      activeMonth: "2026-05",
      role: "owner",
      memberCount: 2,
      createdAt: "2026-05-01",
      updatedAt: "2026-05-31",
    },
    {
      id: "space-personal",
      name: "Personal",
      kind: "personal",
      currency: "DOP",
      activeMonth: "2026-05",
      role: "owner",
      memberCount: 1,
      createdAt: "2026-05-01",
      updatedAt: "2026-05-20",
    },
  ],
  subscription: {
    plan: "free",
    aiCreditsUsed: 12,
    aiCreditsLimit: 25,
    storageMbUsed: 18,
    storageMbLimit: 100,
    spacesLimit: 2,
    membersLimit: 2,
  },
  householdName: "Mi Hogar",
  currency: "DOP",
  activeMonth: "2026-05",
  mode: "monthly-plan",
  accounts: [
    { id: "cash", name: "Efectivo", kind: "cash", balanceCents: 1245000, currency: "DOP", defaultForCapture: true, includeInNetWorth: true, confirmedBalanceCents: 1245000, lastConfirmedAt: "2026-05-01" },
    { id: "bank", name: "Cuenta corriente", kind: "bank", balanceCents: 4280000, currency: "DOP", includeInNetWorth: true, confirmedBalanceCents: 4280000, lastConfirmedAt: "2026-05-01" },
    { id: "card", name: "Tarjeta credito", kind: "credit", balanceCents: -3180000, currency: "DOP", includeInNetWorth: true, confirmedBalanceCents: -3180000, lastConfirmedAt: "2026-05-01" },
    { id: "invest", name: "Inversion", kind: "investment", balanceCents: 9000000, currency: "DOP", includeInNetWorth: true, confirmedBalanceCents: 9000000, lastConfirmedAt: "2026-05-01" },
  ],
  categories: [
    { id: "salary", group: "income", name: "Salario", subcategories: ["Salario TSC", "Consultorio", "Comisiones"], plannedCents: 3850000, source: "starter" },
    { id: "housing", group: "essentials", name: "Hogar", subcategories: ["Renta", "Electricidad", "Agua", "Internet"], plannedCents: 1070000, source: "starter" },
    { id: "food", group: "essentials", name: "Comida", subcategories: ["Supermercado", "Colmado", "Comida fuera"], plannedCents: 520000, source: "starter" },
    { id: "transport", group: "essentials", name: "Transporte", subcategories: ["Gasolina", "Uber", "Mantenimiento"], plannedCents: 165000, source: "starter" },
    { id: "subscriptions", group: "discretionary", name: "Suscripciones", subcategories: ["Apps", "Musica", "Software", "IA"], plannedCents: 222000, source: "starter" },
    { id: "leisure", group: "discretionary", name: "Ocio e imprevistos", subcategories: ["Salidas", "Restaurantes", "Compras especificas"], plannedCents: 316200, source: "starter" },
    { id: "car-debt", group: "debt", name: "Deudas", subcategories: ["Carro", "Tarjeta", "Prestamo personal"], plannedCents: 280000, source: "starter" },
    { id: "emergency", group: "savings", name: "Ahorro", subcategories: ["Emergencia", "Carro", "Viaje"], plannedCents: 500000, source: "starter" },
    { id: "retirement", group: "investments", name: "Inversiones", subcategories: ["Retiro", "Bolsa", "Negocio"], plannedCents: 250000, source: "starter" },
  ],
  monthlyPlans: [
    { id: "plan-2026-05-salary", month: "2026-05", categoryId: "salary", plannedCents: 3850000, rolloverCents: 0 },
    { id: "plan-2026-05-housing", month: "2026-05", categoryId: "housing", plannedCents: 1070000, rolloverCents: 0 },
    { id: "plan-2026-05-food", month: "2026-05", categoryId: "food", plannedCents: 520000, rolloverCents: 0 },
    { id: "plan-2026-05-transport", month: "2026-05", categoryId: "transport", plannedCents: 165000, rolloverCents: 0 },
    { id: "plan-2026-05-subscriptions", month: "2026-05", categoryId: "subscriptions", plannedCents: 222000, rolloverCents: 0 },
    { id: "plan-2026-05-leisure", month: "2026-05", categoryId: "leisure", plannedCents: 316200, rolloverCents: 0 },
    { id: "plan-2026-05-car-debt", month: "2026-05", categoryId: "car-debt", plannedCents: 280000, rolloverCents: 0 },
    { id: "plan-2026-05-emergency", month: "2026-05", categoryId: "emergency", plannedCents: 500000, rolloverCents: 0 },
    { id: "plan-2026-05-retirement", month: "2026-05", categoryId: "retirement", plannedCents: 250000, rolloverCents: 0 },
  ],
  transactions: [
    {
      id: "t1",
      type: "income",
      date: "2026-05-02",
      description: "Pago consultorio",
      categoryId: "salary",
      subcategory: "Consultorio",
      accountId: "bank",
      merchant: "Consultorio",
      tags: ["variable"],
      originalAmountCents: 2050000,
      originalCurrency: "DOP",
      amountCents: 2050000,
      baseCurrency: "DOP",
      exchangeRate: 1,
      exchangeRateDate: "2026-05-02",
      exchangeRateSource: "same_currency",
      status: "approved",
      createdBy: "Owner",
    },
    {
      id: "t2",
      type: "expense",
      date: "2026-05-06",
      description: "Renta",
      categoryId: "housing",
      subcategory: "Renta",
      accountId: "bank",
      merchant: "Propietario",
      tags: ["recurrente"],
      originalAmountCents: 950000,
      originalCurrency: "DOP",
      amountCents: 950000,
      baseCurrency: "DOP",
      exchangeRate: 1,
      exchangeRateDate: "2026-05-06",
      exchangeRateSource: "same_currency",
      status: "approved",
      createdBy: "Owner",
    },
    {
      id: "t3",
      type: "expense",
      date: "2026-05-11",
      description: "Supermercado familiar",
      categoryId: "food",
      subcategory: "Supermercado",
      accountId: "card",
      merchant: "Supermercado",
      tags: ["familia"],
      originalAmountCents: 186450,
      originalCurrency: "DOP",
      amountCents: 186450,
      baseCurrency: "DOP",
      exchangeRate: 1,
      exchangeRateDate: "2026-05-11",
      exchangeRateSource: "same_currency",
      status: "approved",
      createdBy: "Member",
    },
    {
      id: "t4",
      type: "expense",
      date: "2026-05-15",
      description: "Amazon Prime",
      categoryId: "subscriptions",
      subcategory: "Apps",
      accountId: "card",
      merchant: "Amazon",
      tags: ["revision"],
      originalAmountCents: 1499,
      originalCurrency: "USD",
      amountCents: 88591,
      baseCurrency: "DOP",
      exchangeRate: 59.1,
      exchangeRateDate: "2026-05-15",
      exchangeRateSource: "manual",
      status: "needs_review",
      createdBy: "Owner",
    },
    {
      id: "t5",
      type: "expense",
      date: "2026-05-20",
      description: "Gasolina",
      categoryId: "transport",
      subcategory: "Gasolina",
      accountId: "cash",
      merchant: "Estacion",
      tags: [],
      originalAmountCents: 140000,
      originalCurrency: "DOP",
      amountCents: 140000,
      baseCurrency: "DOP",
      exchangeRate: 1,
      exchangeRateDate: "2026-05-20",
      exchangeRateSource: "same_currency",
      status: "approved",
      createdBy: "Owner",
    },
  ],
  comments: [
    {
      id: "comment-t3-1",
      targetType: "transaction",
      targetId: "t3",
      authorMemberId: "m2",
      authorName: "Miembro",
      body: "Este gasto fue supermercado familiar, no ocio.",
      createdAt: "2026-05-12T09:30:00.000Z",
    },
  ],
  receipts: [
    {
      id: "receipt-prime",
      fileName: "amazon-prime-mayo.png",
      contentType: "image/png",
      source: "receipt",
      status: "needs_review",
      createdAt: "2026-05-15",
      transactionId: "t4",
      amountCents: 1499,
      currency: "USD",
      date: "2026-05-15",
      merchant: "Amazon",
      extractedText: "Amazon Prime USD 14.99",
      note: "Confirmar tasa y categoria.",
    },
  ],
  review: [
    { id: "r1", reason: "uncategorized", title: "Amazon Prime", subtitle: "Sin categoria segura - tarjeta credito", amountCents: -88591, action: "Clasificar", targetType: "transaction", targetId: "t4" },
    { id: "r2", reason: "duplicate", title: "Starbucks", subtitle: "Mismo monto, mismo dia", amountCents: -32500, action: "Son dos compras" },
    { id: "r3", reason: "balance_adjustment", title: "Cuenta corriente", subtitle: "Diferencia detectada vs saldo manual", amountCents: 450000, action: "Aceptar ajuste", targetType: "account", targetId: "bank" },
  ],
  recurringRules: [
    {
      id: "rr-rent",
      name: "Renta",
      type: "expense",
      categoryId: "housing",
      accountId: "bank",
      amountCents: 950000,
      currency: "DOP",
      frequency: "monthly",
      nextDate: "2026-06-06",
      merchant: "Propietario",
      note: "Confirmar antes de cerrar el mes.",
      active: true,
    },
    {
      id: "rr-prime",
      name: "Amazon Prime",
      type: "expense",
      categoryId: "subscriptions",
      accountId: "card",
      amountCents: 1499,
      currency: "USD",
      frequency: "monthly",
      nextDate: "2026-06-15",
      merchant: "Amazon",
      note: "Se registra en USD y queda con tasa fijada.",
      active: true,
    },
  ],
  automationRules: [
    {
      id: "ar-supermercado",
      name: "Supermercados a comida",
      matchText: "supermercado",
      categoryId: "food",
      accountId: "card",
      merchant: "Supermercado",
      subcategory: "Supermercado",
      tag: "familia",
      active: true,
    },
    {
      id: "ar-gasolina",
      name: "Gasolina a transporte",
      matchText: "gasolina",
      categoryId: "transport",
      accountId: "cash",
      merchant: "Estacion",
      subcategory: "Gasolina",
      active: true,
    },
  ],
  ruleApplications: [
    {
      id: "ra-seed-supermercado",
      ruleId: "ar-supermercado",
      ruleName: "Supermercados a comida",
      kind: "automation",
      transactionId: "t2",
      transactionDescription: "Supermercado Nacional",
      summary: "Clasifico Supermercado Nacional como Comida familiar.",
      status: "classified",
      createdAt: "2026-05-12T09:35:00.000Z",
    },
  ],
  goals: [
    { id: "g1", name: "Fondo de emergencia", targetCents: 15000000, savedCents: 6200000, due: "2026-12" },
    { id: "g2", name: "Carro", targetCents: 8000000, savedCents: 2100000, due: "2027-03" },
  ],
  debts: [
    { id: "d1", name: "Tarjeta credito", balanceCents: 3180000, originalBalanceCents: 4200000, rate: 0.48, minimumCents: 180000, strategy: "avalanche" },
    { id: "d2", name: "Prestamo carro", balanceCents: 12200000, originalBalanceCents: 15000000, rate: 0.18, minimumCents: 280000, strategy: "snowball" },
  ],
  netWorth: [
    { id: "nw1", name: "Efectivo y bancos", kind: "asset", group: "bank", amountCents: 5525000 },
    { id: "nw2", name: "Inversiones", kind: "asset", group: "investment", amountCents: 9000000 },
    { id: "nw3", name: "Deudas", kind: "liability", group: "debt", amountCents: 15380000 },
  ],
  members: [
    { id: "m1", name: "Propietario", role: "owner", avatar: "PO", email: "owner@example.local" },
    { id: "m2", name: "Miembro", role: "editor", avatar: "MI" },
  ],
  aiSettings: {
    enabled: true,
    provider: "local",
    saveHistory: true,
    allowReceiptText: true,
  },
  aiActions: [
    {
      id: "ai-1",
      kind: "text_capture",
      provider: "local",
      status: "suggested",
      inputPreview: "Pague 750 en farmacia con tarjeta por medicina",
      outputSummary: "Sugerencia de gasto en salud/farmacia pendiente de confirmacion.",
      creditsUsed: 0,
      createdAt: "2026-05-10T10:00:00.000Z",
    },
  ],
  notificationSettings: {
    daily_capture: true,
    recurring: true,
    budget_risk: true,
    month_close: true,
    balance_confirm: true,
    debt_payment: true,
    goal_progress: true,
    movement_review: true,
    receipts: true,
  },
  monthClosings: [
    {
      id: "close-2026-04",
      month: "2026-04",
      incomeCents: 4320000,
      outflowCents: 3915000,
      remainderCents: 405000,
      savingsRate: 0.14,
      netWorthCents: -900000,
      closedAt: "2026-04-30",
      notes: "Primer cierre de referencia para comparar tendencia.",
    },
  ],
};
